name: app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_strategy: ^0.3.0
  go_router: ^17.0.0
  
  http: ^1.6.0
  skeletonizer: ^2.1.0+1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true