name: app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^17.0.0
  
  http: ^1.6.0
  skeletonizer: ^2.1.0+1

  universal_html: ^2.3.0
  provider: ^6.1.5+1
  
  intl: ^0.20.2
  
dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true