name: ext

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  js: ^0.7.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  assets:
    - web/assets/chrome_interop.js

  uses-material-design: true